// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MunicipalityTaxesAPI.ContextConfiguration;

#nullable disable

namespace MunicipalityTaxesAPI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MunicipalityTaxesAPI.Entities.TaxEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("municipality");

                    b.Property<double>("TaxRate")
                        .HasColumnType("float")
                        .HasColumnName("rate");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("taxes", (string)null);
                });

            modelBuilder.Entity("MunicipalityTaxesAPI.Entities.TaxScheduleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime")
                        .HasColumnName("period_end");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime")
                        .HasColumnName("period_start");

                    b.Property<int>("TaxId")
                        .HasColumnType("int")
                        .HasColumnName("tax_id");

                    b.HasKey("Id");

                    b.HasIndex("TaxId")
                        .IsUnique();

                    b.ToTable("tax_schedules", (string)null);
                });

            modelBuilder.Entity("MunicipalityTaxesAPI.Entities.TaxScheduleEntity", b =>
                {
                    b.HasOne("MunicipalityTaxesAPI.Entities.TaxEntity", "Tax")
                        .WithOne("TaxSchedule")
                        .HasForeignKey("MunicipalityTaxesAPI.Entities.TaxScheduleEntity", "TaxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("MunicipalityTaxesAPI.Entities.TaxEntity", b =>
                {
                    b.Navigation("TaxSchedule");
                });
#pragma warning restore 612, 618
        }
    }
}
